### ISSUE TITLE
mex fortran

### ISSUE THREAD

**Issue by liugx1997** [equipez/test_matlab#2]
Hello teacher, I would like to ask you about the problem of FORTRAN invocation by MATLAB. I am running MATLAB on Windows, and I have generated mexW64 file, but it will crash if I use MATLAB to call. Could you help me find the problem?

**Comment by zaikunzhang** [comment]
Hello, thank you for your attention to this repo. However, I am only able to answer questions directly related to my code. 

For debugging of MEX functions, I suggest you refer to MathWorks' official documentation or the customer support of MATLAB. 

Thanks again.
